Project RegistryApi {
	database_type: 'RegistryApiDB'
	Node: '''
		# RegistryApi Database
		**ERD elaborado para o banco de dados da RegistryApi**
	'''
}

Table users {
	id                    uuid            [not null, pk, default: `uuid_generate_v4()`]
	name                  varchar(120)    [not null]
	unique_registry_id    uuid            [not null, ref: - unique_registries.id]
	phone_number          bigint          [null]
	password              char(60)        [not null]
	tfa                   smallint        [not null, default: 0]
	created_at            timestamp       [not null, default: `now()`]
	updated_at            timestamp       [not null, default: `now()`]
}

Table condominiums {
	id                   uuid            [not null, pk, default: `uuid_generate_v4()`]
	human_readable_id    char(6)
	owner_id             uuid            [not null, ref: - users.id]
	name                 varchar(120)    [not null, unique]
	cep                  int             [not null]
	num                  int             [not null, note: 'Número do condomínio']
	cnpj                 bigint          [not null, unique]
	reference            varchar(60)     [null]
	district             varchar(140)    [not null]
	city                 varchar(140)    [not null]
	state                varchar(140)    [not null]
	complement           varchar(60)     [null]
	created_at           timestamp       [not null, default: `now()`]
	updated_at           timestamp       [not null, default: `now()`]
}

Table condominium_members {
	id                     uuid                [not null, pk, default: `uuid_generate_v4()`]
	condominium_id         uuid                [not null, ref: > condominiums.id]
	user_id                uuid                [not null, ref: > users.id]

	unique_registry_id     uuid                [not null, ref: > unique_registries.id]
	role                   smallint            [not null, default: 0]

	created_at             timestamp           [not null, default: `now()`]
	updated_at             timestamp           [not null, default: `now()`]

    Indexes {
	    (unique_registry_id, user_id) [name: 'UQ_condominium_members_unique_registry_id_condominium_id']
		unique_registry_id [unique]
		condominium_id [unique]
	}

	Indexes {
		(condominium_id, user_id) [name: 'UQ_condominium_members_user_id_condominium_id']
		user_id [unique]
		condominium_id [unique]
	}
}

Table unique_registries {
	id                  uuid            [not null, pk]
	cpf                 bigint          [null, unique]
	email               varchar(320)    [not null, unique]
}

Table community_infos {
    member_id           uuid            [not null, pk, ref: - condominium_members.id]
	apartment_number    int             [null]
	block               varchar(6)      [null]
	updated_at          timestamp       [not null, default: `now()`]
}

Table condominium_requests {
    user_id             uuid          [not null, pk, ref: > users.id]
	condominium_id      uuid          [not null, pk, ref: > condominiums.id]
	message             varchar(320)  [null]
	created_at          timestamp     [not null, default: `now()`]
	unique_registry_id  uuid          [not null, ref: > unique_registries.id]

	Indexes {
	   (user_id, condominium_id) [name: 'UQ_condominium_requests_user_condominium_id']
	   user_id [unique]
	   condominium_id [unique]
	}
}
