name: CD - Deploy devtool on Dockerhub

on:
  push:
    branches: 
      - "main"
      - "release/**"

concurrency:
  group: 'devtool-image'
  cancel-in-progress: true

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - name: Docker hub login
        id: docker-hub-login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - uses: docker/build-push-action@v5
        name: Build and push app image
        id: build-and-push-app
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_APP_IMAGE_TAG}}-devtool
